
Collecting tasks from: tasks.py
======================= Running: [96mrobot_spare_bin_python[0m ========================
[96mrobot_spare_bin_python[0m status: [91mFAIL
[0m[91m
Page.goto: Timeout 30000ms exceeded.
Call log:
navigating to "https://www.latimes.com/", waiting until "load"

[0m=============== Full Traceback (running [96mrobot_spare_bin_python[0m) ================
[91mTraceback (most recent call last):
  File "/home/gellanz/.robocorp/holotree/96113aa_b1f3c24_09529949/lib/python3.10/site-packages/robocorp/tasks/_commands.py", line 440, in run
    result = task.run(*args, **kwargs)
  File "/home/gellanz/.robocorp/holotree/96113aa_b1f3c24_09529949/lib/python3.10/site-packages/robocorp/tasks/_task.py", line 89, in run
    return self.method(*args, **kwargs)
  File "/home/gellanz/projects/news_rpa/tasks.py", line 10, in robot_spare_bin_python
    news_locator = robot.navigate()
  File "/home/gellanz/projects/news_rpa/news_robot.py", line 17, in navigate
    self.browser.goto("https://www.latimes.com/")
  File "/home/gellanz/.robocorp/holotree/96113aa_b1f3c24_09529949/lib/python3.10/site-packages/robocorp/browser/__init__.py", line 224, in goto
    p.goto(url)
  File "/home/gellanz/.robocorp/holotree/96113aa_b1f3c24_09529949/lib/python3.10/site-packages/playwright/sync_api/_generated.py", line 8686, in goto
    self._sync(
  File "/home/gellanz/.robocorp/holotree/96113aa_b1f3c24_09529949/lib/python3.10/site-packages/playwright/_impl/_sync_base.py", line 115, in _sync
    return task.result()
  File "/home/gellanz/.robocorp/holotree/96113aa_b1f3c24_09529949/lib/python3.10/site-packages/playwright/_impl/_page.py", line 519, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "/home/gellanz/.robocorp/holotree/96113aa_b1f3c24_09529949/lib/python3.10/site-packages/playwright/_impl/_frame.py", line 145, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "/home/gellanz/.robocorp/holotree/96113aa_b1f3c24_09529949/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 59, in send
    return await self._connection.wrap_api_call(
  File "/home/gellanz/.robocorp/holotree/96113aa_b1f3c24_09529949/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 514, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded.
Call log:
navigating to "https://www.latimes.com/", waiting until "load"


[0m================================================================================
Robocorp Log (html): /home/gellanz/projects/news_rpa/output/log.html
